### ISSUE TITLE
Digital bits representation

### ISSUE THREAD

**Issue by kunalg123** [VSD-DACteam/avsddac_3v3#1]
Hi Avinash
Instead of mentioning D0 to D9 bits individually, you can club all of them into a single D[0:9] 

Thanks

**Comment by VSD-DACteam** [comment]
Hi Kunal,
I have made the necessary changes in digital bits representation. Check it out and see if you might want to close the issue.

**Comment by kunalg123** [comment]
Looks fine
Closing
