### ISSUE TITLE
Regarding Netlist file

### ISSUE THREAD

**Issue by yalamanchilivahini5** [VSD-DACteam/avsddac_3v3#4]
Hi DACteam,

I think the netlist file name is "10bit.cir.out", it is not "10bitdac.cir". You can check it once.

**Comment by VSD-DACteam** [comment]
Hi Vahini, 

Apologies for inaccurate information. I have uploaded the file again with proper name and extention. You can have a look at it now.

Thankyou

**Comment by yalamanchilivahini5** [comment]
Hi DACteam,

Looks good.
Closing issue now.

Thanks
